
# Global options
baseURL = "http://saptarshic.com/"
canonifyURLs = true
defaultContentLanguage = "en"
disableKinds = ["taxonomy", "taxonomyTerm"]
languageCode = "en"
theme = "barks"
title = "Saptarshi Chakraborty"
enableRobotsTXT = true

# Main menu
[[menu.main]]
    name = "Home"
    url  = "/"
    weight = 1
#[[menu.main]]
#    name = "About me"
#    url  = "/about"
#    weight = 2
[[menu.main]]
    name = "Research"
    url  = "/research"
    weight = 3
#[[menu.main]]
#    name = "CV"
#    url  = "/cv.pdf"
#    weight = 3
[[menu.main]]
    name = "Teaching"
    url  = "/teaching"
    weight = 4
[[menu.main]]
    name = "Contact"
    url  = "/contact"
    weight = 5    

[sitemap]
  changefreq = 'daily'
  filename = 'sitemap.xml'
  priority = 0.5

# Customization options
[params]

    [params.head]
        author = "Saptarshi Chakraborty"
        custom_css = "/custom.css"
        description = "Hi, I'm Saptarshi"
        keywords = ["Statistics", "Computer Science", "academic", "PhD", "Berkeley", "ISI"]

    [params.navigation]
        show_navigation = true

    [params.footer]
        show_footer = true

    [params.typography]
#        title_font = "Urbanist"
        title_font = "Cutive Mono"
        body_font = "Source Sans Pro"

    [params.colors]
        theme_color = "#333333"
        background_color = "#fcfbf9"
        text_color = "#333333"
        link_color = "#17442a"

    [params.social]
        [params.social.email]
            name = "E-Mail"
            class = "fas fa-envelope"
            url = "mailto:saptarshic@berkeley.edu"
            weight = 1
        #[params.social.github]
        #    name = "GitHub"
        #    class = "fab fa-github"
        #    url = "https://github.com/anirbanc96"
        #    weight = 2
        [params.social.google_scholar]
            name = "Google Scholar"
            class = "ai ai-google-scholar"
            url = "https://scholar.google.com/citations?user=BAH6owQAAAAJ&hl=en"
            weight = 3
        #[params.social.institution]
        #    name = "My institution"
        #    class = "fas fa-university"
        #    url = ""
        #    weight = 5
        #[params.social.linkedin]
        #    name = "LinkedIn"
        #    class = "fab fa-linkedin"
        #    url = "https://www.linkedin.com/in/anirban-chatterjee-99742611b/"
        #    weight = 6
        #[params.social.orcid]
        #    name = "ORCID iD"
        #    class = "fab fa-orcid"
        #    url = "https://orcid.org/0000-0002-8862-8649"
        #    weight = 7


# Options for Markdown renderer
[markup]

    [markup.goldmark.renderer]
        unsafe = true
        xHTML = true

    [markup.highlight]
        style = 'dracula'
